import {
  Patient,
  Doctor,
  User,
  Service,
  Appointment,
  DashboardStats,
} from "../types";

export const mockPatients: Patient[] = [
  {
    id: "1",
    firstName: "María",
    lastName: "González",
    email: "maria.gonzalez@email.com",
    phone: "+51 987 654 321",
    dateOfBirth: "1985-03-15",
    address: "Av. Los Incas 123, Imperial, Cañete",
    emergencyContact: {
      name: "Carlos González",
      phone: "+51 987 654 322",
      relationship: "Esposo",
    },
    medicalHistory: ["Hipertensión", "Diabetes tipo 2"],
    allergies: ["Penicilina"],
    lastVisit: "2024-01-15",
    nextAppointment: "2024-02-15",
    status: "active",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-15",
  },
  {
    id: "2",
    firstName: "José",
    lastName: "Rodríguez",
    email: "jose.rodriguez@email.com",
    phone: "+51 987 654 323",
    dateOfBirth: "1990-07-22",
    address: "Calle Las Flores 456, Imperial, Cañete",
    emergencyContact: {
      name: "Ana Rodríguez",
      phone: "+51 987 654 324",
      relationship: "Madre",
    },
    medicalHistory: [],
    allergies: [],
    lastVisit: "2024-01-20",
    status: "active",
    createdAt: "2024-01-05",
    updatedAt: "2024-01-20",
  },
  {
    id: "3",
    firstName: "Carmen",
    lastName: "Silva",
    email: "carmen.silva@email.com",
    phone: "+51 987 654 325",
    dateOfBirth: "1978-11-08",
    address: "Jr. San Martín 789, Imperial, Cañete",
    emergencyContact: {
      name: "Luis Silva",
      phone: "+51 987 654 326",
      relationship: "Hermano",
    },
    medicalHistory: ["Asma"],
    allergies: ["Látex"],
    lastVisit: "2024-01-10",
    nextAppointment: "2024-02-20",
    status: "active",
    createdAt: "2023-12-15",
    updatedAt: "2024-01-10",
  },
];

export const mockDoctors: Doctor[] = [
  {
    id: "1",
    firstName: "Dr. Luis",
    lastName: "Mendoza",
    email: "luis.mendoza@clinicadental.com",
    phone: "+51 987 111 222",
    specialization: "Odontología General",
    licenseNumber: "COP-12345",
    experience: 15,
    schedule: {
      Lunes: { start: "08:00", end: "17:00", available: true },
      Martes: { start: "08:00", end: "17:00", available: true },
      Miércoles: { start: "08:00", end: "17:00", available: true },
      Jueves: { start: "08:00", end: "17:00", available: true },
      Viernes: { start: "08:00", end: "16:00", available: true },
      Sábado: { start: "08:00", end: "12:00", available: true },
      Domingo: { start: "", end: "", available: false },
    },
    status: "active",
    createdAt: "2023-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "2",
    firstName: "Dra. Ana",
    lastName: "Torres",
    email: "ana.torres@clinicadental.com",
    phone: "+51 987 111 223",
    specialization: "Ortodoncista",
    licenseNumber: "COP-54321",
    experience: 10,
    schedule: {
      Lunes: { start: "09:00", end: "18:00", available: true },
      Martes: { start: "09:00", end: "18:00", available: true },
      Miércoles: { start: "09:00", end: "18:00", available: true },
      Jueves: { start: "09:00", end: "18:00", available: true },
      Viernes: { start: "09:00", end: "17:00", available: true },
      Sábado: { start: "", end: "", available: false },
      Domingo: { start: "", end: "", available: false },
    },
    status: "active",
    createdAt: "2023-03-01",
    updatedAt: "2024-01-01",
  },
];

export const mockServices: Service[] = [
  {
    id: "1",
    name: "Limpieza Dental",
    description: "Limpieza profesional y profilaxis dental",
    duration: 60,
    price: 80,
    category: "Prevención",
    isActive: true,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "2",
    name: "Consulta General",
    description: "Examen dental completo y diagnóstico",
    duration: 30,
    price: 50,
    category: "Consulta",
    isActive: true,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "3",
    name: "Empaste Dental",
    description: "Restauración dental con resina",
    duration: 90,
    price: 120,
    category: "Restauración",
    isActive: true,
    requirements: ["Anestesia local"],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "4",
    name: "Extracción Dental",
    description: "Extracción simple de pieza dental",
    duration: 45,
    price: 100,
    category: "Cirugía",
    isActive: true,
    requirements: ["Anestesia local", "Antibióticos post-operatorios"],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "5",
    name: "Blanqueamiento Dental",
    description: "Blanqueamiento profesional en consultorio",
    duration: 120,
    price: 300,
    category: "Estética",
    isActive: true,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
];

export const mockUsers: User[] = [
  {
    id: "1",
    firstName: "Admin",
    lastName: "Sistema",
    email: "admin@clinicadental.com",
    role: "admin",
    permissions: [],
    status: "active",
    lastLogin: "2024-01-25",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-25",
  },
  {
    id: "2",
    firstName: "Luis",
    lastName: "Mendoza",
    email: "luis.mendoza@clinicadental.com",
    role: "doctor",
    permissions: [],
    status: "active",
    lastLogin: "2024-01-24",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-24",
  },
  {
    id: "3",
    firstName: "Ana",
    lastName: "Torres",
    email: "ana.torres@clinicadental.com",
    role: "doctor",
    permissions: [],
    status: "active",
    lastLogin: "2024-01-24",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-24",
  },
  {
    id: "4",
    firstName: "Patricia",
    lastName: "Vega",
    email: "patricia.vega@clinicadental.com",
    role: "staff",
    permissions: [],
    status: "active",
    lastLogin: "2024-01-25",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-25",
  },
];

export const dashboardStats: DashboardStats = {
  totalPatients: 156,
  activePatients: 142,
  todayAppointments: 12,
  monthlyRevenue: 15500,
  doctorsAvailable: 2,
  pendingAppointments: 8,
};
